apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: # POD TEMPLATE
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: nginx
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007