apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: # POD TEMPLATE
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: nginx
        ports:
        - containerPort: 80  
