apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
spec:
  replicas:  {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.deployment.label}}
  template: # POD TEMPLATE
    metadata:
      labels:
        app: {{.Values.deployment.label}}
    spec:
      containers:
      - name: {{.Values.deployment.container_name}}
        image: {{.Values.deployment.image}}
        ports:
        - containerPort: {{.Values.deployment.port}}
